export const ITEMS_FETCH_START = "ITEMS_FETCH_START";
export const ITEMS_FETCH_EMPTY = "ITEMS_FETCH_EMPTY";
export const ITEMS_FETCH_END = "ITEMS_FETCH_END";
export const SEARCH_BY_NAME_RESET = "SEARCH_BY_NAME_RESET";
export const SEARCH_BY_NAME_SET = "SEARCH_BY_NAME_SET";
export const DETAIL_ITEM_FETCH_START = "DETAIL_ITEM_FETCH_START";
export const DETAIL_ITEM_FETCH_END = "DETAIL_ITEM_FETCH_END";
export const DETAIL_ITEM_FETCH_ERROR = "DETAIL_ITEM_FETCH_ERROR";

